spring:
  application:
    name: pingme
  datasource:
    url: jdbc:mysql://localhost:3306/pingme_db?allowPublicKeyRetrieval=true&useSSL=false
    username: pmapp
    password: "e9p7s6y2!@"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    path: /swagger-ui  # Swagger UI 경로 변경
    disable-swagger-default-url: true
    operations-sorter: method  # 메서드 순으로 정렬
    tags-sorter: alpha  # 태그를 알파벳 순으로 정렬
  info:
    title: "PingMe API 문서"
    description: "PingMe SNS 프로젝트의 API 명세서입니다."
    version: "1.0.0"